# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-23 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.ClassList', verbose_name='所报班级'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Campuses'),
        ),
    ]
