# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-25 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='菜单名')),
                ('icon', models.CharField(blank=True, max_length=32, null=True, verbose_name='菜单图标')),
                ('priority', models.IntegerField(blank=True, help_text='菜单的显示顺序，优先级越小显示越靠前', null=True, verbose_name='显示优先级')),
                ('parent', models.ForeignKey(blank=True, help_text='如果添加的是子菜单，请选择父菜单', null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Menu', verbose_name='父级菜单')),
            ],
            options={
                'verbose_name': '菜单表',
                'verbose_name_plural': '菜单表',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['id'], 'verbose_name': '权限表', 'verbose_name_plural': '权限表'},
        ),
        migrations.RemoveField(
            model_name='permission',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='show',
        ),
        migrations.AlterField(
            model_name='permission',
            name='icon',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='权限图标'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=32, verbose_name='权限名'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='如果添加的是子权限，请选择父权限', null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Permission', verbose_name='父级权限'),
        ),
        migrations.AddField(
            model_name='permission',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Menu', verbose_name='对应菜单'),
        ),
    ]
